@extends('errors.layout')
@section('code', 'ЗАБАГАТО ЗАПИТІВ')
@section('title', 'Трохи забагато спроб')
@section('message', 'Зачекайте хвилину й спробуйте ще раз - це тимчасове обмеження для захисту від перевантаження.')
@section('reload', 1)
